name: Production AZ Rollout with Health Check and Rollback

# This workflow is manually triggered from GitHub UI
on:
  workflow_dispatch:
    inputs:
      service:
        description: "Name of the service (matches the mapping YAML)"
        required: true
      branch:
        description: "Git branch to deploy"
        default: "main"

jobs:
  deploy:
    name: Deploy to Production AZs
    runs-on: ubuntu-latest
    environment: production

    steps:

    ######################################################
    # 1️⃣ CHECKOUT ORCHESTRATOR REPO
    #    Contains the service mapping YAML that lists
    #    all AZ apps per environment.
    ######################################################
    - name: Checkout orchestrator repo
      uses: actions/checkout@v4

    ######################################################
    # 2️⃣ PARSE MAPPING FILE FOR PRODUCTION AZs
    #    Reads ./services/<service>.yaml to get all AZs
    ######################################################
    - name: Parse mapping for production AZs
      id: mapping
      uses: mikefarah/yq@v4
      with:
        cmd: yq e '.apps.production' ./services/${{ github.event.inputs.service }}.yaml

    - name: Output parsed mapping
      run: echo "Parsed AZ mapping: ${{ steps.mapping.outputs.result }}"

    ######################################################
    # 3️⃣ EXTRACT AZ APP NAMES INTO OUTPUTS
    ######################################################
    - name: Set AZ app names
      id: set-az
      run: |
        echo "az1=$(echo '${{ steps.mapping.outputs.result }}' | yq e '.az1' -)" >> $GITHUB_OUTPUT
        echo "az2=$(echo '${{ steps.mapping.outputs.result }}' | yq e '.az2' -)" >> $GITHUB_OUTPUT
        echo "az3=$(echo '${{ steps.mapping.outputs.result }}' | yq e '.az3' -)" >> $GITHUB_OUTPUT

    ######################################################
    # 4️⃣ CHECKOUT THE ACTUAL SERVICE CODE
    #    Pulls the specified branch from the service repo
    ######################################################
    - name: Checkout service repo
      uses: actions/checkout@v4
      with:
        repository: writetojags/${{ github.event.inputs.service }}-repo
        ref: ${{ github.event.inputs.branch }}
        path: service-code

    ######################################################
    # 5️⃣ DEPLOY AND HEALTH CHECK FOR AZ1
    ######################################################
    - name: Deploy to AZ1
      id: deploy-az1
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ steps.set-az.outputs.az1 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: ${{ github.event.inputs.branch }}
        appdir: service-code

    - name: Health Check AZ1
      run: |
        curl -f https://${{ steps.set-az.outputs.az1 }}.herokuapp.com/actuator/health

    ######################################################
    # 6️⃣ DEPLOY AND HEALTH CHECK FOR AZ2
    ######################################################
    - name: Deploy to AZ2
      id: deploy-az2
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ steps.set-az.outputs.az2 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: ${{ github.event.inputs.branch }}
        appdir: service-code

    - name: Health Check AZ2
      run: |
        curl -f https://${{ steps.set-az.outputs.az2 }}.herokuapp.com/actuator/health

    ######################################################
    # 7️⃣ DEPLOY AND HEALTH CHECK FOR AZ3
    ######################################################
    - name: Deploy to AZ3
      id: deploy-az3
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ steps.set-az.outputs.az3 }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: ${{ github.event.inputs.branch }}
        appdir: service-code

    - name: Health Check AZ3
      run: |
        curl -f https://${{ steps.set-az.outputs.az3 }}.herokuapp.com/actuator/health

  ######################################################
  # 8️⃣ ROLLBACK JOB (if deploy job fails)
  #    Can be customized to alert via Slack, email, etc.
  ######################################################
  rollback:
    name: Rollback if deploy fails
    needs: deploy
    if: failure()
    runs-on: ubuntu-latest

    steps:
    - name: Log Rollback
      run: |
        echo "Deploy failed on one or more AZs."
        echo "Triggering rollback procedure..."
        # Here you can add logic to re-deploy previous versions
        # Or notify via Slack/email using a webhook
