name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package --file ./event-service/pom.xml

    # -------- Deploy to AZ1 --------
    - name: Deploy to AZ1
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: event-service-prod-az1
        heroku_email: ${{ secrets.HEROKU_EMAIL }}

    - name: Health Check AZ1
      run: |
        echo "Waiting for AZ1 to boot..."
        sleep 20
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.PROD_APP_HEALTH_URL_AZ1 }}")
        if [ "$STATUS" -ne 200 ]; then
          echo "AZ1 health check failed with status $STATUS"
          exit 1
        else
          echo "AZ1 health check passed."
        fi

    # -------- Deploy to AZ2 --------
    - name: Deploy to AZ2
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: event-service-prod-az2
        heroku_email: ${{ secrets.HEROKU_EMAIL }}

    - name: Health Check AZ2
      run: |
        echo "Waiting for AZ2 to boot..."
        sleep 20
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.PROD_APP_HEALTH_URL_AZ2 }}")
        if [ "$STATUS" -ne 200 ]; then
          echo "AZ2 health check failed with status $STATUS"
          exit 1
        else
          echo "AZ2 health check passed."
        fi

    # -------- Deploy to AZ3 --------
    - name: Deploy to AZ3
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: event-service-prod-az3
        heroku_email: ${{ secrets.HEROKU_EMAIL }}

    - name: Health Check AZ3
      run: |
        echo "Waiting for AZ3 to boot..."
        sleep 20
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.PROD_APP_HEALTH_URL_AZ3 }}")
        if [ "$STATUS" -ne 200 ]; then
          echo "AZ3 health check failed with status $STATUS"
          exit 1
        else
          echo "AZ3 health check passed."
        fi

    # -------- Slack Notification --------
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
