name: Production One Click Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      RC_COMMIT:
        description: 'Orchestrator commit SHA or branch to deploy'
        required: true
        default: 'main'


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      # Event Driven app names
      EVENT_DRIVEN_APP_AZ1: ${{ secrets.EVENT_DRIVEN_APP_AZ1 }}
      EVENT_DRIVEN_APP_AZ2: ${{ secrets.EVENT_DRIVEN_APP_AZ2 }}
      EVENT_DRIVEN_APP_AZ3: ${{ secrets.EVENT_DRIVEN_APP_AZ3 }}

      # Event Service app names
      EVENT_SERVICE_APP_AZ1: ${{ secrets.EVENT_SERVICE_APP_AZ1 }}
      EVENT_SERVICE_APP_AZ2: ${{ secrets.EVENT_SERVICE_APP_AZ2 }}
      EVENT_SERVICE_APP_AZ3: ${{ secrets.EVENT_SERVICE_APP_AZ3 }}

      # Tolerant Reader app names
      TOLERANT_READER_APP_AZ1: ${{ secrets.TOLERANT_READER_APP_AZ1 }}
      TOLERANT_READER_APP_AZ2: ${{ secrets.TOLERANT_READER_APP_AZ2 }}
      TOLERANT_READER_APP_AZ3: ${{ secrets.TOLERANT_READER_APP_AZ3 }}

    steps:

    - name: ✅ Checkout Orchestrator Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ✅ Print Environment Variables for Debugging
      run: |
        echo "RC_COMMIT=${{ github.event.inputs.RC_COMMIT }}"
        echo "HEROKU_API_KEY=${HEROKU_API_KEY:0:4}****"
        echo "EVENT_DRIVEN_APP_AZ1=$EVENT_DRIVEN_APP_AZ1"
        echo "EVENT_SERVICE_APP_AZ1=$EVENT_SERVICE_APP_AZ1"
        echo "TOLERANT_READER_APP_AZ1=$TOLERANT_READER_APP_AZ1"

    - name: ✅ Checkout Event Driven Repo
      uses: actions/checkout@v3
      with:
        repository: writetojags/event-driven-repo
        token: ${{ secrets.EVENT_DRIVEN_REPO_TOKEN }}
        ref: master
        path: event-driven
        fetch-depth: 0

    - name: ✅ Checkout Event Service Repo
      uses: actions/checkout@v3
      with:
        repository: writetojags/event-driven-service-repo
        token: ${{ secrets.EVENT_SERVICE_REPO_TOKEN }}
        ref: main
        path: event-service
        fetch-depth: 0

    - name: ✅ Checkout Tolerant Reader Repo
      uses: actions/checkout@v3
      with:
        repository: writetojags/tolerant-reader-service
        token: ${{ secrets.TOLERANT_READER_REPO_TOKEN }}
        ref: main
        path: tolerant-reader
        fetch-depth: 0

    - name: 🚀 Deploy Event Driven Service to Production
      working-directory: ./event-driven
      run: |
        bash ../.github/scripts/deploy-prod.sh event_driven \
          "${{ github.event.inputs.RC_COMMIT }}" \
          "$EVENT_DRIVEN_APP_AZ1" "$EVENT_DRIVEN_APP_AZ2" "$EVENT_DRIVEN_APP_AZ3"

    - name: 🚀 Deploy Event Service to Production
      working-directory: ./event-service
      run: |
        bash ../.github/scripts/deploy-prod.sh event_service \
          "${{ github.event.inputs.RC_COMMIT }}" \
          "$EVENT_SERVICE_APP_AZ1" "$EVENT_SERVICE_APP_AZ2" "$EVENT_SERVICE_APP_AZ3"

    - name: 🚀 Deploy Tolerant Reader Service to Production
      working-directory: ./tolerant-reader
      run: |
        bash ../.github/scripts/deploy-prod.sh tolerant_reader \
          "${{ github.event.inputs.RC_COMMIT }}" \
          "$TOLERANT_READER_APP_AZ1" "$TOLERANT_READER_APP_AZ2" "$TOLERANT_READER_APP_AZ3"
