name: Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --file ./event-service/pom.xml

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: event-service-stage-app
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Wait for app to boot
        run: sleep 20

      - name: Perform Health Check
        run: |
          echo "Checking health endpoint..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.STAGE_APP_HEALTH_URL }}")
          if [ "$STATUS" -ne 200 ]; then
            echo "Health check failed with status $STATUS"
            exit 1
          else
            echo "Health check passed with status $STATUS"
          fi

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

